name: Blogger Auto Poster (Baghdad 10:00 & 18:00)

on:
  schedule:
    # GitHub = UTC ; Baghdad = UTC+3
    - cron: '0 7 * * *'   # 10:00 Baghdad
    - cron: '0 15 * * *'  # 18:00 Baghdad
  workflow_dispatch:
    inputs:
      slot:
        description: '0 صباح / 1 مساء'
        required: true
        default: '0'

permissions:
  contents: read

concurrency:
  group: blogger-autopost
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    # == كل المتغيّرات هنا، بما فيها مفاتيح الصور ==
    env:
      # أسرار أساسية
      GEMINI_API_KEY:      ${{ secrets.GEMINI_API_KEY }}
      BLOG_URL:            ${{ secrets.BLOG_URL }}
      CLIENT_ID:           ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET:       ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN:       ${{ secrets.REFRESH_TOKEN }}

      # مفاتيح صور (اختياري) — نفس التي نجحت بالتجربة
      PEXELS_API_KEY:      ${{ secrets.PEXELS_API_KEY }}
      PIXABAY_API_KEY:     ${{ secrets.PIXABAY_API_KEY }}
      UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
      # لو أردت صورة ثابتة مؤقتاً للغلاف (اختياري)
      FEATURED_IMAGE_URL:  ${{ secrets.FEATURED_IMAGE_URL }}

      # إعدادات سلوك السكربت
      PUBLISH_MODE:        live          # live أو draft
      TREND_GEO:           IQ            # للدعم الإخباري إن لزم
      TREND_GEO_LIST:      ""            # مثال: "IQ,SA,AE,EG"
      TOPIC_WINDOW_DAYS:   "14"          # منع تكرار موضوع مقارب خلال X يوم
      TZ:                  Asia/Baghdad  # لتوحيد الطباعة الزمنية

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install google-api-python-client google-auth requests markdown bleach
          fi

      - name: Decide SLOT (0/1)
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            # تمييز أيّ الجدولتين نحن فيهما (UTC 07:00/15:00)
            if [[ "${{ github.event.schedule }}" == "0 15 * * *" ]]; then
              echo "SLOT=1" >> $GITHUB_ENV
            else
              echo "SLOT=0" >> $GITHUB_ENV
            fi
          else
            echo "SLOT=${{ inputs.slot }}" >> $GITHUB_ENV
          fi
          echo "Slot=$SLOT"

      - name: Post to Blogger
        run: |
          python - <<'PY'
          import os
          from main import make_article_once
          slot = int(os.environ.get("SLOT","0"))
          make_article_once(slot)
          PY
