name: Blogger Auto Poster (Baghdad 10:00 & 18:00)

on:
  schedule:
    - cron: "0 7 * * *"    # 10:00 Baghdad (UTC+3)
    - cron: "0 15 * * *"   # 18:00 Baghdad (UTC+3)
  workflow_dispatch:
    inputs:
      slot:
        description: "0 صباح، 1 مساء"
        required: true
        default: "0"

permissions:
  contents: read

concurrency:
  group: blogger-auto-publisher
  cancel-in-progress: true

env:
  GEMINI_API_KEY:   ${{ secrets.GEMINI_API_KEY }}
  BLOG_URL:         ${{ secrets.BLOG_URL }}
  CLIENT_ID:        ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET:    ${{ secrets.CLIENT_SECRET }}
  REFRESH_TOKEN:    ${{ secrets.REFRESH_TOKEN }}
  PUBLISH_MODE:     live
  TZ:               Asia/Baghdad

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Resolve slot
        id: slot
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            SLOT="${{ github.event.inputs.slot }}"
          else
            case "${{ github.event.schedule }}" in
              "0 7 * * *")  SLOT="0" ;;
              "0 15 * * *") SLOT="1" ;;
              *)            SLOT="0" ;;
            esac
          fi
          echo "slot=$SLOT" >> "$GITHUB_OUTPUT"
          echo "Resolved SLOT=$SLOT"

      - name: Post to Blogger (update-or-insert)
        shell: bash
        env:
          SLOT: ${{ steps.slot.outputs.slot }}
        run: |
          cat > runner.py <<'PY'
          import os, sys
          from main import make_article_once
          try:
              slot = int(os.environ.get("SLOT","0"))
              if slot not in (0,1):
                  raise ValueError("Invalid slot")
              make_article_once(slot)
              print("OK")
          except Exception as e:
              print("ERROR:", e, file=sys.stderr)
              sys.exit(1)
          PY
          python runner.py
