name: Blogger Auto Poster (Baghdad 10:00 & 18:00)

on:
  schedule:
    # GitHub = UTC ; Baghdad = UTC+3
    - cron: '0 7 * * *'   # 10:00 Baghdad
    - cron: '0 15 * * *'  # 18:00 Baghdad
  workflow_dispatch:
    inputs:
      slot:
        description: '0 صباح / 1 مساء'
        required: true
        default: '0'

permissions:
  contents: read

concurrency:
  group: blogger-autopost
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      BLOG_URL:       ${{ secrets.BLOG_URL }}
      CLIENT_ID:      ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET:  ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN:  ${{ secrets.REFRESH_TOKEN }}
      PUBLISH_MODE:   live
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Decide SLOT (0/1)
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            if [[ "${{ github.event.schedule }}" == "0 15 * * *" ]]; then
              echo "SLOT=1" >> $GITHUB_ENV
            else
              echo "SLOT=0" >> $GITHUB_ENV
            fi
          else
            echo "SLOT=${{ inputs.slot }}" >> $GITHUB_ENV
          fi
          echo "Slot=$SLOT"

      - name: Post to Blogger
        run: |
          python - <<'PY'
          import os
          from main import make_article_once
          slot = int(os.environ.get("SLOT","0"))
          make_article_once(slot)
          PY
